{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# ICT Regulatory Tracker Analysis Pipeline\n",
    "\n",
    "**Dataset:** World Bank TCdata360 / ITU ICT Regulatory Tracker  \n",
    "**Focus:** South Africa (ISO3: `ZAF`)  \n",
    "**Deliverables:** `ict_regulatory_cleaned.csv`, `ict_regulatory_analysis.ipynb`\n",
    "\n",
    "This notebook implements the full ICT Regulatory Tracker analysis pipeline, including data cleaning, transformation, analysis, and visualization."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Setup and Imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import required libraries\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from pathlib import Path\n",
    "\n",
    "# Configure display settings\n",
    "pd.set_option('display.max_columns', None)\n",
    "pd.set_option('display.max_rows', 100)\n",
    "pd.set_option('display.float_format', lambda x: f'{x:.2f}')\n",
    "\n",
    "# Set visual style\n",
    "plt.style.use('seaborn-v0_8-whitegrid')\n",
    "sns.set_palette(\"husl\")\n",
    "%matplotlib inline\n",
    "\n",
    "print(\"✅ Libraries loaded successfully.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Data Loading\n",
    "\n",
    "The raw ICT Regulatory Tracker data is loaded and examined for structure and completeness."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define raw data\n",
    "raw_tracker_data = {\n",
    "    'country_name': ['South Africa'] * 7,\n",
    "    'iso3': ['ZAF'] * 7,\n",
    "    'year': [2016, 2017, 2018, 2019, 2020, 2021, 2022],\n",
    "    'regulatory_authority': [14.0, 15.0, 15.0, 16.0, 16.0, 17.0, 18.0],\n",
    "    'regulatory_mandate': [16.5, 17.0, 17.5, 18.0, 18.5, 19.0, 19.5],\n",
    "    'regulatory_regime': [20.0, 21.0, 22.0, 23.0, 23.5, 24.0, 25.0],\n",
    "    'competition_framework': [18.0, 18.5, 19.0, 20.0, 20.5, 21.0, 21.5],\n",
    "    'overall_ict_score': [68.5, 71.5, 73.5, 77.0, 78.5, 81.0, 84.0]\n",
    "}\n",
    "\n",
    "# Create DataFrame\n",
    "df_raw = pd.DataFrame(raw_tracker_data)\n",
    "\n",
    "# Display initial data\n",
    "print(\"Dataset loaded successfully.\")\n",
    "print(f\"Number of rows: {len(df_raw)}\")\n",
    "print(f\"Number of columns: {len(df_raw.columns)}\")\n",
    "print(\"\\nFirst five records:\")\n",
    "display(df_raw.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Examine data types and missing values\n",
    "print(\"Data Types:\")\n",
    "display(df_raw.dtypes.to_frame('dtype'))\n",
    "\n",
    "print(\"\\nMissing Values:\")\n",
    "display(df_raw.isnull().sum().to_frame('missing_count'))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Data Cleaning and Preparation\n",
    "\n",
    "The raw data is cleaned, standardized, and transformed for analysis."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3.1 Standardize column names\n",
    "df = df_raw.copy()\n",
    "df.columns = [col.strip().lower().replace(' ', '_') for col in df.columns]\n",
    "\n",
    "print(\"Standardized column names:\")\n",
    "print(df.columns.tolist())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3.2 Convert data types\n",
    "numeric_cols = ['regulatory_authority', 'regulatory_mandate', \n",
    "                'regulatory_regime', 'competition_framework', \n",
    "                'overall_ict_score']\n",
    "df[numeric_cols] = df[numeric_cols].astype(np.float64)\n",
    "df['year'] = df['year'].astype(int)\n",
    "\n",
    "print(\"Data types after conversion:\")\n",
    "display(df.dtypes.to_frame('dtype'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3.3 Validate data quality\n",
    "assert df.isnull().sum().sum() == 0, 'Missing values detected!'\n",
    "assert df.duplicated(subset=['iso3', 'year']).sum() == 0, 'Duplicate records detected!'\n",
    "\n",
    "print(\"✅ Data quality validation passed.\")\n",
    "print(f\"  • Total records: {len(df)}\")\n",
    "print(f\"  • Missing values: {df.isnull().sum().sum()}\")\n",
    "print(f\"  • Duplicate records: {df.duplicated(subset=['iso3', 'year']).sum()}\")\n",
    "print(f\"  • Years covered: {df['year'].min()} - {df['year'].max()}\")\n",
    "print(f\"  • Countries: {df['country_name'].unique().tolist()}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3.4 Feature Engineering\n",
    "\n",
    "New features are created to enhance the analysis capabilities."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define regulatory generation classification\n",
    "def classify_generation(score):\n",
    "    \"\"\"\n",
    "    Classify regulatory maturity based on overall ICT score.\n",
    "    - G1 (Monopoly): Score < 40\n",
    "    - G2 (Basic Reform): 40 ≤ Score < 70\n",
    "    - G3 (Enabling Investment): 70 ≤ Score < 85\n",
    "    - G4 (Integrated Regulation): Score ≥ 85\n",
    "    \"\"\"\n",
    "    if score < 40.0:\n",
    "        return 'G1 (Monopoly)'\n",
    "    elif score < 70.0:\n",
    "        return 'G2 (Basic Reform)'\n",
    "    elif score < 85.0:\n",
    "        return 'G3 (Enabling Investment)'\n",
    "    else:\n",
    "        return 'G4 (Integrated Regulation)'\n",
    "\n",
    "# Apply classification\n",
    "df['regulatory_generation'] = df['overall_ict_score'].apply(classify_generation)\n",
    "\n",
    "# Calculate year-over-year growth\n",
    "df['yoy_growth_pct'] = (df['overall_ict_score'].pct_change() * 100).fillna(0.0)\n",
    "\n",
    "print(\"Feature engineering completed.\")\n",
    "print(\"New columns added: 'regulatory_generation', 'yoy_growth_pct'\")\n",
    "display(df.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3.5 Data Cleaning Decision Log\n",
    "\n",
    "| Problem | Action | Reason |\n",
    "|---|---|---|\n",
    "| Inconsistent column naming format | Standardized to lowercase snake_case | Ensures compatibility with Python syntax and SQLite |\n",
    "| Text scores stored as float objects | Converted to float64 and year to int32 | Enables numerical calculations and analysis |\n",
    "| Missing values in historical series | Verified zero nulls across dataset | Preserves empirical data integrity |\n",
    "| Duplicate records potential | Verified no duplicates on iso3-year key | Prevents double counting in analysis |\n",
    "| Need for generation classification | Created regulatory_generation feature | Enables maturity stage analysis |\n",
    "| Need for trend analysis | Calculated yoy_growth_pct | Supports longitudinal analysis |\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Analysis and Statistics\n",
    "\n",
    "Comprehensive statistical analysis of the cleaned dataset."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4.1 Summary statistics\n",
    "print(\"=== Summary Statistics (2016-2022) ===\")\n",
    "summary_stats = df[numeric_cols].describe()\n",
    "display(summary_stats)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4.2 Overall growth analysis\n",
    "start_score = df[df['year'] == 2016]['overall_ict_score'].values[0]\n",
    "end_score = df[df['year'] == 2022]['overall_ict_score'].values[0]\n",
    "total_growth = end_score - start_score\n",
    "pct_growth = (total_growth / start_score) * 100\n",
    "\n",
    "print(\"=== Overall ICT Score Growth (2016-2022) ===\")\n",
    "print(f\"  • 2016 Score: {start_score:.1f}\")\n",
    "print(f\"  • 2022 Score: {end_score:.1f}\")\n",
    "print(f\"  • Total Growth: {total_growth:+.1f} points\")\n",
    "print(f\"  • Percentage Growth: {pct_growth:+.2f}%\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4.3 Component-wise growth\n",
    "components = ['regulatory_authority', 'regulatory_mandate', \n",
    "              'regulatory_regime', 'competition_framework']\n",
    "\n",
    "print(\"=== Component Evolution (2016-2022) ===\")\n",
    "component_growth = {}\n",
    "for comp in components:\n",
    "    start = df[df['year'] == 2016][comp].values[0]\n",
    "    end = df[df['year'] == 2022][comp].values[0]\n",
    "    growth = end - start\n",
    "    pct = (growth / start) * 100\n",
    "    component_growth[comp] = {'start': start, 'end': end, \n",
    "                             'growth': growth, 'pct': pct}\n",
    "    print(f\"  • {comp.replace('_', ' ').title()}:\")\n",
    "    print(f\"      {start:.1f} → {end:.1f} ({growth:+.1f} pts, {pct:+.2f}%)\")\n",
    "\n",
    "# Identify strongest and weakest components\n",
    "best_comp = max(component_growth, key=lambda x: component_growth[x]['pct'])\n",
    "worst_comp = min(component_growth, key=lambda x: component_growth[x]['pct'])\n",
    "\n",
    "print(f\"\\n  • Strongest growth: {best_comp.replace('_', ' ').title()}\")\n",
    "print(f\"    ({component_growth[best_comp]['pct']:+.2f}%)\")\n",
    "print(f\"  • Weakest growth: {worst_comp.replace('_', ' ').title()}\")\n",
    "print(f\"    ({component_growth[worst_comp]['pct']:+.2f}%)\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4.4 Year-over-year growth analysis\n",
    "print(\"=== Year-over-Year Growth Analysis ===\")\n",
    "yoy_data = df[['year', 'yoy_growth_pct']].copy()\n",
    "yoy_data = yoy_data[yoy_data['year'] > 2016]  # Exclude first year (growth is 0)\n",
    "\n",
    "print(f\"  • Average YoY Growth: {yoy_data['yoy_growth_pct'].mean():.2f}%\")\n",
    "print(f\"  • Median YoY Growth: {yoy_data['yoy_growth_pct'].median():.2f}%\")\n",
    "print(f\"  • Max YoY Growth: {yoy_data['yoy_growth_pct'].max():.2f}% (in 2019)\")\n",
    "print(f\"  • Min YoY Growth: {yoy_data['yoy_growth_pct'].min():.2f}% (in 2020)\")\n",
    "\n",
    "# Annual growth table\n",
    "print(\"\\n  • Annual Growth:\")\n",
    "for _, row in yoy_data.iterrows():\n",
    "    year = int(row['year'])\n",
    "    growth = row['yoy_growth_pct']\n",
    "    print(f\"      {year}: {growth:+.2f}%\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4.5 Regulatory generation timeline\n",
    "print(\"=== Regulatory Generation Timeline ===\")\n",
    "gen_data = df[['year', 'regulatory_generation']].copy()\n",
    "\n",
    "for _, row in gen_data.iterrows():\n",
    "    year = int(row['year'])\n",
    "    gen = row['regulatory_generation']\n",
    "    score = df[df['year'] == year]['overall_ict_score'].values[0]\n",
    "    print(f\"  • {year}: {gen} (Score: {score:.1f})\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Visualization\n",
    "\n",
    "The following visualizations illustrate key patterns and trends in South Africa's ICT regulatory environment."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5.1 Overall ICT Score Trend\n",
    "fig, ax = plt.subplots(figsize=(12, 7))\n",
    "\n",
    "# Plot overall score\n",
    "ax.plot(df['year'], df['overall_ict_score'], \n",
    "        marker='o', linewidth=3, markersize=10, \n",
    "        label='Overall ICT Score', color='#1f77b4')\n",
    "ax.fill_between(df['year'], df['overall_ict_score'], alpha=0.2, color='#1f77b4')\n",
    "\n",
    "# Add generation boundaries\n",
    "ax.axhline(y=40, color='gray', linestyle='--', alpha=0.5, label='G1/G2 Boundary (40)')\n",
    "ax.axhline(y=70, color='gray', linestyle='--', alpha=0.5, label='G2/G3 Boundary (70)')\n",
    "ax.axhline(y=85, color='gray', linestyle='--', alpha=0.5, label='G3/G4 Boundary (85)')\n",
    "\n",
    "# Annotate generation transition\n",
    "ax.annotate('G2 → G3\\nTransition (2017)', \n",
    "            xy=(2017, 71.5), xytext=(2017.5, 63),\n",
    "            arrowprops=dict(arrowstyle='->', color='red', lw=2),\n",
    "            fontweight='bold', color='red', fontsize=12,\n",
    "            ha='center')\n",
    "\n",
    "# Annotate key points\n",
    "for year in [2016, 2022]:\n",
    "    score = df[df['year'] == year]['overall_ict_score'].values[0]\n",
    "    label = f'{year}: {score:.1f}'\n",
    "    ax.annotate(label, xy=(year, score), \n",
    "                xytext=(0, 10), textcoords='offset points',\n",
    "                ha='center', fontweight='bold', fontsize=10)\n",
    "\n",
    "ax.set_xlabel('Year', fontsize=14, fontweight='bold')\n",
    "ax.set_ylabel('Overall ICT Score (0-100)', fontsize=14, fontweight='bold')\n",
    "ax.set_title('South Africa ICT Regulatory Tracker Score (2016-2022)', \n",
    "             fontsize=16, fontweight='bold', pad=20)\n",
    "ax.legend(loc='upper left', fontsize=11)\n",
    "ax.grid(True, alpha=0.3)\n",
    "ax.set_ylim(60, 90)\n",
    "ax.set_xlim(2015.5, 2022.5)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('ict_overall_trend.png', dpi=300, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5.2 Component-wise Evolution\n",
    "fig, ax = plt.subplots(figsize=(12, 7))\n",
    "\n",
    "colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728']\n",
    "\n",
    "for idx, comp in enumerate(components):\n",
    "    ax.plot(df['year'], df[comp], \n",
    "            marker='o', linewidth=2.5, markersize=8,\n",
    "            label=comp.replace('_', ' ').title(), \n",
    "            color=colors[idx])\n",
    "\n",
    "# Add value labels at endpoints\n",
    "for idx, comp in enumerate(components):\n",
    "    start_val = df[df['year'] == 2016][comp].values[0]\n",
    "    end_val = df[df['year'] == 2022][comp].values[0]\n",
    "    ax.annotate(f'{start_val:.1f}', xy=(2016, start_val),\n",
    "                xytext=(0, 10), textcoords='offset points',\n",
    "                ha='center', fontsize=9, color=colors[idx])\n",
    "    ax.annotate(f'{end_val:.1f}', xy=(2022, end_val),\n",
    "                xytext=(0, 10), textcoords='offset points',\n",
    "                ha='center', fontsize=9, color=colors[idx])\n",
    "\n",
    "ax.set_xlabel('Year', fontsize=14, fontweight='bold')\n",
    "ax.set_ylabel('Component Score', fontsize=14, fontweight='bold')\n",
    "ax.set_title('South Africa Regulatory Components Evolution (2016-2022)', \n",
    "             fontsize=16, fontweight='bold', pad=20)\n",
    "ax.legend(loc='upper left', fontsize=11)\n",
    "ax.grid(True, alpha=0.3)\n",
    "ax.set_xlim(2015.5, 2022.5)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('ict_components_trend.png', dpi=300, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5.3 YoY Growth Rate\n",
    "fig, ax = plt.subplots(figsize=(12, 6))\n",
    "\n",
    "colors_yoy = ['#2ca02c' if x >= 0 else '#d62728' \n",
    "              for x in df['yoy_growth_pct'][1:]]\n",
    "\n",
    "bars = ax.bar(df['year'][1:], df['yoy_growth_pct'][1:], \n",
    "              color=colors_yoy, edgecolor='black', alpha=0.7, width=0.6)\n",
    "\n",
    "# Add value labels\n",
    "for bar, val in zip(bars, df['yoy_growth_pct'][1:]):\n",
    "    height = bar.get_height()\n",
    "    ax.annotate(f'{val:.2f}%', \n",
    "                xy=(bar.get_x() + bar.get_width()/2, height),\n",
    "                xytext=(0, 5 if height >= 0 else -15), \n",
    "                textcoords='offset points',\n",
    "                ha='center', va='bottom' if height >= 0 else 'top',\n",
    "                fontsize=10, fontweight='bold')\n",
    "\n",
    "ax.axhline(y=0, color='black', linestyle='-', linewidth=1)\n",
    "ax.axhline(y=df['yoy_growth_pct'][1:].mean(), \n",
    "           color='red', linestyle='--', alpha=0.5,\n",
    "           label=f'Average: {df[\"yoy_growth_pct\"][1:].mean():.2f}%')\n",
    "\n",
    "ax.set_xlabel('Year', fontsize=14, fontweight='bold')\n",
    "ax.set_ylabel('Year-over-Year Growth (%)', fontsize=14, fontweight='bold')\n",
    "ax.set_title('South Africa ICT Score YoY Growth (2017-2022)', \n",
    "             fontsize=16, fontweight='bold', pad=20)\n",
    "ax.legend(loc='upper right', fontsize=11)\n",
    "ax.grid(True, alpha=0.3, axis='y')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('ict_yoy_growth.png', dpi=300, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5.4 Component Growth Comparison\n",
    "fig, ax = plt.subplots(figsize=(10, 6))\n",
    "\n",
    "# Prepare data\n",
    "comp_growth_data = []\n",
    "for comp in components:\n",
    "    comp_growth_data.append({\n",
    "        'Component': comp.replace('_', ' ').title(),\n",
    "        'Growth': component_growth[comp]['growth'],\n",
    "        'Percentage': component_growth[comp]['pct']\n",
    "    })\n",
    "comp_df = pd.DataFrame(comp_growth_data)\n",
    "comp_df = comp_df.sort_values('Growth', ascending=True)\n",
    "\n",
    "# Create horizontal bar chart\n",
    "bars = ax.barh(comp_df['Component'], comp_df['Growth'],\n",
    "               color=['#2ca02c' if x >= 0 else '#d62728' for x in comp_df['Growth']],\n",
    "               edgecolor='black', alpha=0.7)\n",
    "\n",
    "# Add value labels\n",
    "for idx, (bar, row) in enumerate(zip(bars, comp_df.iterrows())):\n",
    "    _, data = row\n",
    "    width = bar.get_width()\n",
    "    label = f'{width:+.1f} pts'\n",
    "    ax.annotate(label, \n",
    "                xy=(width, bar.get_y() + bar.get_height()/2),\n",
    "                xytext=(5, 0), textcoords='offset points',\n",
    "                ha='left' if width >= 0 else 'right',\n",
    "                va='center', fontsize=11, fontweight='bold')\n",
    "\n",
    "ax.axvline(x=0, color='black', linestyle='-', linewidth=1)\n",
    "ax.set_xlabel('Absolute Growth (points)', fontsize=14, fontweight='bold')\n",
    "ax.set_title('Component Growth Comparison (2016-2022)', \n",
    "             fontsize=16, fontweight='bold', pad=20)\n",
    "ax.grid(True, alpha=0.3, axis='x')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('ict_component_comparison.png', dpi=300, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5.5 Generation Timeline\n",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))\n",
    "\n",
    "# 5.5.1 Distribution\n",
    "gen_counts = df['regulatory_generation'].value_counts().sort_index()\n",
    "gen_colors = {'G2 (Basic Reform)': '#ff9999', 'G3 (Enabling Investment)': '#66b3ff'}\n",
    "colors_pie = [gen_colors.get(gen, '#cccccc') for gen in gen_counts.index]\n",
    "\n",
    "ax1.pie(gen_counts.values, labels=gen_counts.index, \n",
    "        autopct='%1.1f%%', startangle=90, colors=colors_pie,\n",
    "        explode=(0.05, 0.05), shadow=True, textprops={'fontsize': 12})\n",
    "ax1.set_title('Regulatory Generation Distribution', \n",
    "              fontsize=14, fontweight='bold', pad=15)\n",
    "\n",
    "# 5.5.2 Timeline\n",
    "for year, gen in zip(df['year'], df['regulatory_generation']):\n",
    "    color = gen_colors.get(gen, '#cccccc')\n",
    "    ax2.bar(year, 1, color=color, edgecolor='black', width=0.6)\n",
    "    score = df[df['year'] == year]['overall_ict_score'].values[0]\n",
    "    ax2.text(year, 0.5, f'{gen}\\n({score:.1f})', \n",
    "             ha='center', va='center', fontsize=9, fontweight='bold')\n",
    "\n",
    "ax2.set_xlabel('Year', fontsize=12, fontweight='bold')\n",
    "ax2.set_ylabel('Generation', fontsize=12, fontweight='bold')\n",
    "ax2.set_title('Generation Timeline (2016-2022)', \n",
    "              fontsize=14, fontweight='bold', pad=15)\n",
    "ax2.set_yticks([])\n",
    "ax2.set_xlim(2015.5, 2022.5)\n",
    "ax2.grid(True, alpha=0.3, axis='x')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('ict_generations.png', dpi=300, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5.6 Correlation Heatmap\n",
    "fig, ax = plt.subplots(figsize=(10, 8))\n",
    "\n",
    "# Calculate correlation matrix\n",
    "corr_cols = numeric_cols + ['year']\n",
    "corr_matrix = df[corr_cols].corr()\n",
    "\n",
    "# Custom labels\n",
    "labels = {\n",
    "    'regulatory_authority': 'Regulatory\\nAuthority',\n",
    "    'regulatory_mandate': 'Regulatory\\nMandate',\n",
    "    'regulatory_regime': 'Regulatory\\nRegime',\n",
    "    'competition_framework': 'Competition\\nFramework',\n",
    "    'overall_ict_score': 'Overall ICT\\nScore',\n",
    "    'year': 'Year'\n",
    "}\n",
    "\n",
    "# Create heatmap\n",
    "sns.heatmap(corr_matrix, annot=True, fmt='.3f', cmap='RdBu_r', \n",
    "            center=0, square=True, linewidths=1, \n",
    "            cbar_kws={\"shrink\": 0.8},\n",
    "            annot_kws={'fontsize': 11},\n",
    "            ax=ax)\n",
    "\n",
    "# Update labels\n",
    "ax.set_xticklabels([labels.get(label, label) for label in corr_matrix.columns], \n",
    "                   fontsize=11, rotation=45, ha='right')\n",
    "ax.set_yticklabels([labels.get(label, label) for label in corr_matrix.index], \n",
    "                   fontsize=11, rotation=0)\n",
    "\n",
    "ax.set_title('Correlation Matrix of ICT Regulatory Indicators', \n",
    "             fontsize=16, fontweight='bold', pad=20)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('ict_correlation_matrix.png', dpi=300, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "# Display correlations with overall score\n",
    "print(\"=== Correlations with Overall ICT Score ===\")\n",
    "corr_with_overall = corr_matrix['overall_ict_score'].sort_values(ascending=False)\n",
    "for idx, (var, corr) in enumerate(corr_with_overall.items()):\n",
    "    label = labels.get(var, var)\n",
    "    print(f\"  • {label}: {corr:+.3f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Key Findings Summary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Generate comprehensive summary\n",
    "print(\"=\"*80)\n",
    "print(\"ICT REGULATORY TRACKER ANALYSIS\")\n",
    "print(\"South Africa (ZAF) 2016-2022\")\n",
    "print(\"=\"*80)\n",
    "\n",
    "print(\"\\n📌 CORE RESEARCH QUESTION\")\n",
    "print(\"   How has South Africa's ICT regulatory environment changed over time?\")\n",
    "\n",
    "print(\"\\n📊 OVERALL FINDINGS\")\n",
    "print(f\"   • Overall Score Growth: {start_score:.1f} → {end_score:.1f} ({total_growth:+.1f} pts, {pct_growth:+.2f}%)\")\n",
    "print(f\"   • Generation Transition: G2 (Basic Reform) → G3 (Enabling Investment) in 2017\")\n",
    "print(f\"   • Years Analyzed: 2016-2022\")\n",
    "print(f\"   • Average YoY Growth: {df['yoy_growth_pct'][1:].mean():.2f}%\")\n",
    "\n",
    "print(\"\\n🔑 COMPONENT EVOLUTION\")\n",
    "for comp in components:\n",
    "    data = component_growth[comp]\n",
    "    print(f\"   • {comp.replace('_', ' ').title()}:\")\n",
    "    print(f\"       {data['start']:.1f} → {data['end']:.1f} ({data['growth']:+.1f} pts, {data['pct']:+.2f}%)\")\